
class Finals:

    # USED IN MARKET
    MARKET_NUM = 2
    KOSPI_MARKET = 0
    KOSDAQ_MARKET = 1
    MARKET_NAMES = ["KOSPI", "KOSDAQ"]

    # USED IN TARGET CONDITION
    KOSPI_SELECT_ONE = 0
    KOSDAQ_SELECT_ONE = 1
    KOSPI_SELECT_ALL = 2
    KOSDAQ_SELECT_ALL = 3
    SEARCH_CONDITION_CODE = 0
    SEARCH_CONDITION_NAME = 1
    NOT_EXIST_MESSAGE = "결과가 존재하지 않습니다."

